name: 'Changelog generator'
description: 'Generate a changelog for your PR'

inputs:
  trigger:
    description: 'The trigger to generate the PR. Could be either "[KEYWORD]", "always" or "none"'
    required: false
    default: 'always'

ouput:
  path:
    description: 'The path to the generated changelog file'
  content:
    description: 'The (string) content of the changelog'

runs:
  using: 'node12'
  main: 'index.js'
