on:
  pull_request:
    types: [opened, reopened]

jobs:
  runChangelog:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/changelog
